In [2]:
import numpy as np

In [2]:

def magnitude_3(a,b,c):

    v = [a,b,c]
     
    return np.linalg.norm(v)
    
magnitude_3(1,2,3) 

3.7416573867739413

In [4]:
def magnitude_complete(*args):               

       
    x = []

    for arg in args:
        x.append(arg)
        print(x)
    return np.linalg.norm(x)

magnitude_complete(1,2,3)       


[1]
[1, 2]
[1, 2, 3]


3.7416573867739413

In [5]:
mat = np.mat('1 -2;1 3')
  
# Original matrix
print(mat)
print("")
evalue, evect = np.linalg.eig(mat)
  
# Eigenvalues of the said matrix"
print(evalue)
print("")
  
# Eigenvectors of the said matrix
print(evect)

[[ 1 -2]
 [ 1  3]]

[2.+1.j 2.-1.j]

[[ 0.81649658+0.j          0.81649658-0.j        ]
 [-0.40824829-0.40824829j -0.40824829+0.40824829j]]


In [ ]:
x = np.array([1, 2, 3, 4])
m = np.mat(x)
m = m.shape[0]
m

In [7]:
def add_vectors(u, v):
    return np.add(u, v)

a = np.array([1,2,3,4,5,6])
b = np.array([9,80,7,7,5,1])

add_vectors(a,b)
 

array([10, 82, 10, 11, 10,  7])

In [15]:
def add_vectors_manualy(u,v):

    l =[]
    for i in range(len(u)):
        l.append(u[i] + v[i])
    return l

a = np.array([1,2,3,4,5,6])
b = np.array([9,80,7,7,5,1])

add_vectors_manualy(a,b)

[10, 82, 10, 11, 10, 7]

In [16]:
def scalar_function(scalar,vector):
    
    return np.array(vector) * scalar

scalar_function(4,[3,4])


array([12, 16])

In [5]:
def dot_product(u, v):
    return np.dot(u,v)





dot_product([1,2,3],[8,6,7])   

41

In [6]:
def copy_matrix(matrix):
    return matrix.copy()

copy_matrix([[1, 2], [3, 4]])    

[[1, 2], [3, 4]]

In [11]:
def add_row(matrix,row):
    return np.vstack([matrix,row])

m = [[1, 7], [8, 5]]
add_row(m, [9, 9])

array([[1, 7],
       [8, 5],
       [9, 9]])

In [12]:
def add_row(matrix):
    new_row=[]
    for row in matrix:
        n_columns=len(row)
        
    for i in range(n_columns):
        new_row.append(0)
    return np.vstack([matrix,new_row])
    

In [14]:
n = [[3, 2, 5], [1, 4, 7]]
add_row(n)

array([[3, 2, 5],
       [1, 4, 7],
       [0, 0, 0]])

In [20]:
def add_column(matrix,column):
    return np.column_stack([matrix,column])

matrix= [[3, 2], [5, 1], [4, 7]]
add_column(matrix,[2, 6,2])


array([[3, 2, 2],
       [5, 1, 6],
       [4, 7, 2]])

In [27]:
def add_matrices(m1, m2):
    m3 = []
    for x,y in zip(m1,m2):
        m3.append(np.add(x,y))
    return np.asmatrix(m3)

c = [[8, 2], [3, 4], [5, 7]]
d = [[3, 2], [9, 2], [10, 12]]

add_matrices(c, d)    


matrix([[11,  4],
        [12,  6],
        [15, 19]])

In [30]:
def add_matrices(m1, m2):

    m1 = np.matrix(m1)
    m2 = np.matrix(m2)
    return m1+m2

c = [[8, 2], [3, 4], [5, 7]]
d = [[3, 2], [9, 2], [10, 12]]

add_matrices(c, d)




matrix([[11,  4],
        [12,  6],
        [15, 19]])

In [32]:
"""daje ten sam wynik co matrix"""

c = [[8, 2], [3, 4], [5, 7]]
d = [[3, 2], [9, 2], [10, 12]]

c = np.array(c)
d = np.array(d)
result = c+d
result  


array([[11,  4],
       [12,  6],
       [15, 19]])

In [35]:
def scalar_mult(s, m):
    m= np.matrix(m)*s
    return m


In [36]:
a = [[1, 2], [3, 4]]
scalar_mult(3, a)

matrix([[ 3,  6],
        [ 9, 12]])

In [42]:
def scalar_mult_flt(s, m):
    m = np.matrix(m)
    dim = np.shape(m)
    v = m.flatten()
    nv = v*s
    print(f'original matrix {m}')
    print(f'shape {dim}')
    print(f'flatten {v}')
    print(f'scalar * flatten {nv}')
    return np.matrix(nv.reshape(dim))
a = [[1, 2], [3, 4], [5,6]]    
scalar_mult_flt(3, a)
# [1, 2, 3, 4]

original matrix [[1 2]
 [3 4]
 [5 6]]
shape (3, 2)
flatten [[1 2 3 4 5 6]]
scalar * flatten [[ 3  6  9 12 15 18]]


matrix([[ 3,  6],
        [ 9, 12],
        [15, 18]])

In [45]:
def matrix_mult(m1, m2):
    a = np.matmul(m1,m2)
    return a

matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])

array([[19, 22],
       [43, 50]])

In [46]:
def transpose(m):
    return np.transpose(m)
    """
     >>> m = [[3, 4, 6]]
     >>> transpose(m)
     [[3], [4], [6]]
     >>> m
     [3, 4, 6]
     >>> m = [[3, 4, 6], [1, 5, 9]]
     >>> transpose(m)
     [[3, 1], [4, 5], [6, 9]]
    """
    
m = [[3, 4, 6]]
transpose(m)

array([[3],
       [4],
       [6]])

In [47]:
def transpose_np(m):
    m = np.array(m)
    return m.T