In [6]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

# Set random seed
np.random.seed(0)

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

In [152]:
#load_iris()

In [125]:
df = load_iris()

In [126]:
df_iris = pd.DataFrame(df.data, columns= df.feature_names)

In [136]:
df_iris["target"] = df.target
df_iris["class"]  = df.target_names[df.target]
df_iris.columns = [col.replace("(cm)", "").strip() for col in df_iris.columns]

In [134]:
# for col in df_iris.columns:
#    col.replace("(cm)", "").strip()
    

    

In [137]:
df_iris.columns

Index(['sepal length', 'sepal width', 'petal length', 'petal width', 'target',
       'class'],
      dtype='object')

In [138]:
df_iris

sepal length  sepal width  petal length  petal width  target      class
0             5.1          3.5           1.4          0.2       0     setosa
1             4.9          3.0           1.4          0.2       0     setosa
2             4.7          3.2           1.3          0.2       0     setosa
3             4.6          3.1           1.5          0.2       0     setosa
4             5.0          3.6           1.4          0.2       0     setosa
..            ...          ...           ...          ...     ...        ...
145           6.7          3.0           5.2          2.3       2  virginica
146           6.3          2.5           5.0          1.9       2  virginica
147           6.5          3.0           5.2          2.0       2  virginica
148           6.2          3.4           5.4          2.3       2  virginica
149           5.9          3.0           5.1          1.8       2  virginica

[150 rows x 6 columns]

In [149]:
X = df_iris.iloc[:,:4]
y = df_iris['target']

In [155]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X,y , test_size =0.2, random_state = 42) 

In [172]:
scalar = StandardScaler()

X_train.loc[:,:] = scalar.fit_transform(X_train)
X_test.loc[:,:] = scalar.transform(X_test)

C:\Users\Wojtek\anaconda3\envs\wojtek\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\Wojtek\anaconda3\envs\wojtek\lib\site-packages\pandas\core\indexing.py:692: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)
C:\Users\Wojtek\anaconda3\envs\wojtek\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable

In [187]:
X_test

sepal length  sepal width  petal length  petal width
73       0.354517    -0.585060      0.557775     0.022248
18      -0.133071     1.650837     -1.161395    -1.179118
118      2.304867    -1.032239      1.818500     1.490583
78       0.232620    -0.361470      0.443164     0.422703
76       1.207795    -0.585060      0.615081     0.289218
31      -0.498762     0.756479     -1.276006    -1.045633
64      -0.254968    -0.361470     -0.072587     0.155733
141      1.329692     0.085709      0.786998     1.490583
68       0.476414    -1.926598      0.443164     0.422703
82      -0.011174    -0.808649      0.099330     0.022248
110      0.842104     0.309299      0.786998     1.090128
12      -1.230143    -0.137880     -1.333312    -1.446088
36      -0.376865     0.980068     -1.390618    -1.312603
9       -1.108246     0.085709     -1.276006    -1.446088
19      -0.864452     1.650837     -1.276006    -1.179118
56       0.598311     0.532889      0.557775     0.556188
104      0.842104    -0.137880      1.188138     1.357098
69      -0.254968    -1.255829      0.099330    -0.111238
55      -0.133071    -0.585060      0.443164     0.155733
132      0.720208    -0.585060      1.073526     1.357098
29      -1.352040     0.309299     -1.218701    -1.312603
127      0.354517    -0.137880      0.672387     0.823158
26      -0.986349     0.756479     -1.218701    -1.045633
128      0.720208    -0.585060      1.073526     1.223613
131      2.548661     1.650837      1.531972     1.090128
145      1.085898    -0.137880      0.844304     1.490583
108      1.085898    -1.255829      1.188138     0.823158
143      1.207795     0.309299      1.245443     1.490583
45      -1.230143    -0.137880     -1.333312    -1.179118
30      -1.230143     0.085709     -1.218701    -1.312603

In [176]:
from sklearn.tree import DecisionTreeClassifier

In [177]:
model = DecisionTreeClassifier()

In [178]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [185]:
predictions = model.predict(X_test)
predictions
#X_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [191]:
y_test

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: target, dtype: int32

In [193]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, predictions)
score

1.0

In [199]:
pd.concat([X_test, y_test], axis = 1)

sepal length  sepal width  petal length  petal width  target
73       0.354517    -0.585060      0.557775     0.022248       1
18      -0.133071     1.650837     -1.161395    -1.179118       0
118      2.304867    -1.032239      1.818500     1.490583       2
78       0.232620    -0.361470      0.443164     0.422703       1
76       1.207795    -0.585060      0.615081     0.289218       1
31      -0.498762     0.756479     -1.276006    -1.045633       0
64      -0.254968    -0.361470     -0.072587     0.155733       1
141      1.329692     0.085709      0.786998     1.490583       2
68       0.476414    -1.926598      0.443164     0.422703       1
82      -0.011174    -0.808649      0.099330     0.022248       1
110      0.842104     0.309299      0.786998     1.090128       2
12      -1.230143    -0.137880     -1.333312    -1.446088       0
36      -0.376865     0.980068     -1.390618    -1.312603       0
9       -1.108246     0.085709     -1.276006    -1.446088       0
19      -0.864452     1.650837     -1.276006    -1.179118       0
56       0.598311     0.532889      0.557775     0.556188       1
104      0.842104    -0.137880      1.188138     1.357098       2
69      -0.254968    -1.255829      0.099330    -0.111238       1
55      -0.133071    -0.585060      0.443164     0.155733       1
132      0.720208    -0.585060      1.073526     1.357098       2
29      -1.352040     0.309299     -1.218701    -1.312603       0
127      0.354517    -0.137880      0.672387     0.823158       2
26      -0.986349     0.756479     -1.218701    -1.045633       0
128      0.720208    -0.585060      1.073526     1.223613       2
131      2.548661     1.650837      1.531972     1.090128       2
145      1.085898    -0.137880      0.844304     1.490583       2
108      1.085898    -1.255829      1.188138     0.823158       2
143      1.207795     0.309299      1.245443     1.490583       2
45      -1.230143    -0.137880     -1.333312    -1.179118       0
30      -1.230143     0.085709     -1.218701    -1.312603       0

In [197]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing'

In [18]:
X = np.random.rand(100)
y = np.zeros(100)

In [19]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
y[np.random.randint(0,50, size = [5])] = 1

In [21]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
pd.Series(y).value_counts()

0.0    95
1.0     5
dtype: int64