In [1]:
import numpy as np

wojtek_array = np.random.random(10)

print(wojtek_array)

print(wojtek_array.size*wojtek_array.itemsize, "bytes")

[0.8507571  0.2777729  0.48046749 0.97753375 0.29219286 0.31460208
 0.22731959 0.65887317 0.32237157 0.2395173 ]
80 bytes


In [2]:
arr = np.array([1,2,3,4])
new_arr = arr[0:3].copy()
new_arr[0:1] = 900
print(arr)
print(new_arr)

[1 2 3 4]
[900   2   3]


In [3]:
arr = np.array([[1,2], [3,4]])
arr[0,1]

2

In [15]:
arr = np.array([[1,2], [3,4], [5,6]])
arr[:,0]

#ze wszystkich 3 wziety kazdy pierwszy element

array([1, 3, 5])

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2[arr2 % 2 ==0]


array([ 2,  4,  6,  8, 10])

In [4]:
for ch in ['a', 'b', 'c', 'd']:
    if ch == 'b':
        continue
    print(ch)

a
c
d


In [18]:
def multiplier(a):
  

    if a % 2 ==0:
        print(f'{a}is multiplier by of 2')
    elif a % 3 == 0:
        print(f'{a} is a multiplier of 3')
    else:
        print(f'{a} in neither a multiplier of 2 or 3')

multiplier(59)
        

59 in neither a multiplier of 2 or 3


In [25]:
a = 18

while True:
    if  a == 5:
        break
   
    print(a)
    a -=1

18
17
16
15
14
13
12
11
10
9
8
7
6


In [35]:
#last 3 elements taken 

l1 = [ 1,2,3,4,5,6,6,7,89,100]
l2 = l[-1:-4:-1]



print(l2)


[100, 89, 7]


In [37]:
#add lists
l1l2 = l1 + l2

print(l1l2)

[1, 2, 3, 4, 5, 6, 6, 7, 89, 100, 100, 89, 7]


In [48]:
d ={ 
    'a': 2,
    'b': 3,
    'c': 5
}

d['d'] = 40

print(f' d= {d}')

print(d.values())
print(d.keys())
print(d.items())

 d= {'a': 2, 'b': 3, 'c': 5, 'd': 40}
dict_values([2, 3, 5, 40])
dict_keys(['a', 'b', 'c', 'd'])
dict_items([('a', 2), ('b', 3), ('c', 5), ('d', 40)])


In [52]:
#set only prints unique elements

a = set ([1,2,3])
b = {2,3,4,3,5,}

print(a.union(b))
print(a.intersection(b))

{1, 2, 3, 4, 5}
{2, 3}


In [58]:
#concatenate int to str
 a = 1 
 s = f'a is {a}'
 s = 'a is '+ str(a)
 s

'a is 1'

In [67]:
s = 'hello world'
print(s.split(" ")) # jak zrobi liste to nie mozna zrobic sptrip dlatego strip robimy zawsze wczesniej
print(s.strip())
print(s.strip().split(' '))

['hello', 'world']
hello world
['hello', 'world']


In [68]:
for index, value in enumerate(['a', 'b']):
    print(index, value)

0 a
1 b


In [70]:
help(set)

NameError: name 'ask' is not defined

In [73]:
import math

In [74]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [75]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [83]:
print(math.log(90))

4.499809670330265


In [86]:
with open ('C:\Users\Wojtek\OneDrive\Desktop\STRIVE SCHOOL\WojtekRepo\1. Python\04. Strings and Files\exercises\text-files',"r" 'blakepoems' ) as file_handler: 
    file_handler.readline()    

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-86-a06f001f2c7a>, line 1)