In [2]:
import cv2
import random

In [ ]:
img = cv2.imread('Green_lion.jpg',1)


In [ ]:
img = cv2.resize(img,(0,0), fx= 0.5 , fy= 0.5)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#save the image
cv2.imwrite('wojtek.jpg', img)

In [ ]:
#rotate the image

img_rotate = cv2.rotate(img,cv2.cv2.ROTATE_90_CLOCKWISE)
cv2.imshow('image',img_rotate)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#slicing image
cv2.imshow('image',img[100:250][50:450])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#adding random pixels
img_c = img.copy()

for i in range(200):
    for j in range(img.shape[0]):
        img_c[i][j] = [random.randint(0,255), random.randint(0,255), random.randint(0,255)]

In [ ]:
cv2.imshow('image',img_c)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
print(img.shape)
print(img.shape[1])

In [ ]:
#copy part of an image to an image
img = cv2.imread('Green_lion.jpg',1)
tag = img[200:400, 750:950]    #mi has to be the same rang betwwen numbers i.e between 200:400 is the smame range as 100:300 czyli 200 pixels
img[100:300, 750:950] = tag

cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
print(img.shape)

In [2]:
import numpy as np
import cv2

In [16]:

#capture video

cap = cv2.VideoCapture(0)

while True:
  ret,frame = cap.read()
  
  #3 is width 4 is height this code get the frame measurments
  width  =int(cap.get(3))
  height  =int(cap.get(4))
  
  
  image =np.zeros(frame.shape, np.uint8)
  
  smaller_frame = cv2.resize(frame,(0,0), fx=0.5, fy=0.5)
  image[:height//2 , :width//2] = cv2.rotate(smaller_frame, cv2.cv2.ROTATE_180)
  image[height//2: , :width//2] = smaller_frame
  image[:height//2 , width//2:] = smaller_frame
  image[height//2: , width//2:] = cv2.rotate(smaller_frame, cv2.cv2.ROTATE_180)
  
  
  cv2.imshow('frame', image)
  if cv2.waitKey(1) == ord('q'):
      break
  
cap.release()
cv2.destroyAllWindows()
    

In [19]:
cap = cv2.VideoCapture(0)

while True:
  ret,frame = cap.read()
  
  #3 is width 4 is height this code get the frame measurments
  width  =int(cap.get(3))
  height  =int(cap.get(4))
  
  img  = cv2.line(frame, (0,0), (width,height),(255,0,0), 10)
  img  = cv2.line(img, (0,height),(width,0), (0,0,255), 18)
  img = cv2.rectangle(img,(100,100), (200,200), (128,128,128), 2)
  img - cv2.circle(img,(300,300), 150, (25,0,0),5) 
  font = cv2.FONT_HERSHEY_SIMPLEX
  img = cv2.putText(img, 'WOJTEK', (250, height -20),font,1, (255,255,255), 5, cv2.LINE_AA)
  
  cv2.imshow('frame', img)
  
  if cv2.waitKey(1) == ord('q'):
      break
  
cap.release()
cv2.destroyAllWindows()

In [19]:
#Tinsae code

import cv2
import numpy as np 


image = cv2.imread('Green_lion.jpg')
background = cv2.imread('night1.jpg')

#background = np.ones(image.shape,dtype=np.uint8)*144

#changing the background size equal to the image
background = cv2.resize(background, (image.shape[1],image.shape[0]), interpolation = cv2.INTER_AREA)
background = cv2.cvtColor(background,cv2.COLOR_BGR2HSV)

hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

lower_green = np.array([36,0,0])
upper_green = np.array([86, 255,255])

#mask for the background
mask = cv2.inRange(hsv, lower_green, upper_green)

mask_inv = cv2.bitwise_not(mask)

background = cv2.bitwise_and(background,background, mask=mask)
target = cv2.bitwise_and(hsv,hsv, mask=mask_inv)
target = cv2.bitwise_or(target,background)
print(mask.shape)
BGR = cv2.cvtColor(target,cv2.COLOR_HSV2BGR)
cv2.imshow('lion',BGR)
cv2.waitKey(0)
cv2.destroyAllWindows()

(720, 1280)


In [14]:
cap = cv2.VideoCapture(0)

while True:
  ret,frame = cap.read()
  
  #3 is width 4 is height this code get the frame measurments
  width  =int(cap.get(3))
  height  =int(cap.get(4))
  
  
  
  hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
  lower_blue = np.array([90,50,50])
  upper_blue = np.array([130,255,255])
  
  mask = cv2.inRange(hsv, lower_blue, upper_blue)
  
  result = cv2.bitwise_and(frame, frame, mask=mask )
  
  cv2.imshow('frame', result)
  
  if cv2.waitKey(1) == ord('q'):
      break
  
cap.release()
cv2.destroyAllWindows()

In [33]:
#corners detection
import numpy as np
import cv2 

path= 'chessboard.png'

img= cv2.imread(path)
img= cv2.resize(img, (0,0), fx=0.5, fy=0.5)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


corners = cv2.goodFeaturesToTrack(gray,100,0.01, 10)
#converting corners to integers
corners = np.int0(corners)
for corner in corners:
    x,y =corner.ravel() 
    cv2.circle(img,(x,y), 5, (255,0,0), -1)

for i in range(len(corners)):
    for j in range(i + 1, len(corners)):
        corner1 = tuple(corners[i][0])
        corner2 = tuple(corners[j][0])
        #GENERATE RANDOM COLORS
        color = tuple(map(lambda x: int(x), np.random.randint(0, 255, size=3)))
        cv2.line(img, corner1, corner2, color, 1)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
print(corners)

[[[300 300]]

 [[299 373]]

 [[226 300]]

 [[373 299]]

 [[300 226]]

 [[226 373]]

 [[373 226]]

 [[373 373]]

 [[226 226]]

 [[448 300]]

 [[151 299]]

 [[300 448]]

 [[299 151]]

 [[373 447]]

 [[447 373]]

 [[152 226]]

 [[226 152]]

 [[226 447]]

 [[152 373]]

 [[447 226]]

 [[373 152]]

 [[152 447]]

 [[447 152]]

 [[447 447]]

 [[152 152]]

 [[299 522]]

 [[ 77 300]]

 [[522 299]]

 [[300  77]]

 [[226 521]]

 [[ 78 373]]

 [[521 226]]

 [[373  78]]

 [[373 521]]

 [[521 373]]

 [[ 78 226]]

 [[226  78]]

 [[447 521]]

 [[521 447]]

 [[ 78 152]]

 [[152  78]]

 [[ 78 447]]

 [[521 152]]

 [[447  78]]

 [[152 521]]

 [[ 78 521]]

 [[521  78]]

 [[521 521]]

 [[ 78  78]]

 [[299 595]]

 [[  4 300]]

 [[595 299]]

 [[300   4]]

 [[  4 373]]

 [[595 226]]

 [[226 595]]

 [[373   4]]

 [[447 595]]

 [[152   4]]

 [[595 447]]

 [[  4 152]]

 [[ 78 595]]

 [[  4 521]]

 [[595  78]]

 [[521   4]]

 [[595 595]]

 [[  4   4]]

 [[374 595]]

 [[595 374]]

 [[  4 225]]

 [[225   4]]

 [[151