In [14]:
# Import needed packages
# You may add or remove packages should you need them
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.datasets import load_iris
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import KFold, LeaveOneOut, cross_val_score

# Set random seed
np.random.seed(0)

# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()

In [19]:
# Load the Iris dataset included with scikit-learn
iris = load_iris()
#iris

In [23]:
# Put data in a pandas DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [43]:
# Add target and class to DataFrame
df['target'] = iris.target
df['class'] = iris.target_names[iris.target]
df.columns = [col.replace("(cm)", " ").strip() for col in df.columns]

In [44]:
# Show 10 random samples
df.sample(10)

sepal length  sepal width  petal length  petal width  target       class
85            6.0          3.4           4.5          1.6       1  versicolor
137           6.4          3.1           5.5          1.8       2   virginica
77            6.7          3.0           5.0          1.7       1  versicolor
108           6.7          2.5           5.8          1.8       2   virginica
122           7.7          2.8           6.7          2.0       2   virginica
104           6.5          3.0           5.8          2.2       2   virginica
121           5.6          2.8           4.9          2.0       2   virginica
12            4.8          3.0           1.4          0.1       0      setosa
31            5.4          3.4           1.5          0.4       0      setosa
96            5.7          2.9           4.2          1.3       1  versicolor

In [38]:
# now... implement the LDA (bear in mind that you do pass it the y's and it is supervised!)
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis()


In [61]:
# same process as always, identify your X's and your y's

X,y = df.iloc[:,0:4], df.iloc[:,-2]
X.shape

(150, 4)

In [58]:
#train-test-split
from sklearn.model_selection import train_test_split
X_train , x_test, Y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)


In [72]:
X_train.shape

(120, 4)

In [66]:
# Scale the X's
scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scled = scaler.transform(X_train)


In [90]:
Y_train.shape

(120,)

In [78]:
# apply the lda transformation
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

model = LinearDiscriminantAnalysis()
model.fit(X_train_scaled, Y_train)


LinearDiscriminantAnalysis()

In [91]:
# select 2 principal components
lda = LDA(n_components =2)

X_train_scaled = lda.fit_transform(X_train_scaled, Y_train)
X_test_scled = lda.transform(X_test_scled)

In [88]:
X_test_scled.shape


(120, 2)

In [92]:
# take a look at the new axes for the data and plot them



array([0.99229795, 0.00770205])

In [94]:
# what about the variability?
model.explained_variance_ratio_

array([0.99229795, 0.00770205])

In [101]:
# Run a Random Forest Classifier with the transformed data
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2 , random_state = 2)
classifier.fit(X_train, Y_train)
y_pred = classifier.predict(x_test)
y_pred


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [2]:
#Check the new acuracy! Is it higher or lower than what you obtain selecting 2 features and applying a Random Forest Directly?

In [106]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test,y_pred)
print(cm)
print(accuracy)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1
