In [3]:
import numpy as np 

def copy_matrix(matrix):
    l=[]
    for i in range(len(matrix)):
        x = sum(u[i] * v[i])
        l.append(x)
    return l   

In [4]:
def copy_matrix(matrix):
    return np.matrix(matrix)

In [13]:
def add_row(matrix,r):
    
    return  np.vstack([matrix,r])
    


In [27]:
m = [[0, 0], [0, 0]]
add_row(m,[0,0])

array([[0, 0],
       [0, 0],
       [0, 0]])

In [38]:
def add_column(matrix):
    m=[]
    a=len(matrix)
    for i in range(a):
        m.append(0)
    return np.column_stack([matrix,m])


In [44]:
n = [[3, 2], [5, 1], [4, 7]]
add_column(n)

array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 0]])

In [48]:
def add_column_np(matrix,col):
    return(np.column_stack([matrix,col]))

In [52]:
n = [[3, 2], [5, 1], [4, 7]]
add_column_np(n,[0,0,9])

array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 9]])