# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [5]:


    




    """
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
    """


'\n  >>> add_vectors([1, 0], [1, 1])\n  [2, 1]\n  >>> add_vectors([1, 2], [1, 4])\n  [2, 6]\n  >>> add_vectors([1, 2, 1], [1, 4, 3])\n  [2, 6, 4]\n  >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])\n  [13, -4, 13, 5]\n  >>> a = [1, 2, 3]\n  >>> b = [1, 1, 1]\n  >>> add_vectors(a, b)\n  [2, 3, 4]\n  >>> a\n  [1, 2, 3]\n  >>> b\n  [1, 1, 1]\n'

In [39]:
import numpy as np
def add_vectors(u, v):
  l=[]
  for i in range(len(u)):
    l.append(u[i] + v[i])
  return l

add_vectors([1, 0,3], [1, 1, 6])




[2, 1, 9]

In [40]:
def add_vectors_np(u, v):
    return np.add(u,v)
add_vectors_np([1, 0], [1, 1])    

array([2, 1])

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [2]:
def scalar_mult(s, v):
  
    """
      >>> scalar_mult(5, [1, 2])
      [5, 10]
      >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
    """

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [67]:
def scalar_mult(s, v):
    l=[]
    for i in range(len(v)):
        l.append(s*(v[i]))
    return l

scalar_mult(5, [1, 2])




[5, 10]

In [71]:
"""shorter version"""
def scalar_short(s,v):
    l = []
    for i in v:
        l.append(s*i)
    return l    
scalar_short(5, [1, 2])

[5, 10]

In [66]:
def scalar_mult_np(s, v):
    return np.array(v)*s

scalar_mult_np(5, [1, 2])
    

array([ 5, 10])

In [69]:
def dot_product(u, v):
    
assert dot_product([1, 1], [1, 1])
2>>> 4])
9
>>> dot_product([1, 2, 1], [1, 4, 3])
12
>>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
0
    

In [108]:
def dot_product(u,v):
    c=[x*y for x,y in zip(u,v)]
    return sum(c)
#dot_product([1, 1], [1, 1])

assert dot_product([1, 2], [1,4]) == 9
assert dot_product([1, 2, 1], [1, 4, 3]) == 12
assert dot_product([2, 0, -1, 1], [1, 5, 2, 0]) == 0

In [102]:
def dot_product(u,v):
   return sum(u[i]*v[i] for i in u)
    
dot_product([1, 1], [1, 1])

2

In [80]:
def dot_product_np(u,v):
    return np.dot(u,v)

In [127]:
dot_product_np([1, 1], [1, 1])

2

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [6]:
def copy_matrix(matrix):
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """

In [120]:
m =[[2,3],[4,2]]
def copy_matrix(matrix):
    
    return matrix.copy()


copy_matrix(m) is m 
copy_matrix(m) == m      

True

In [ ]:
def add_row(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """

In [9]:
def add_row(matrix,r):
    return np.vstack([matrix,r])

m = [[0, 0], [0, 0]]
add_row(m, [1,2])   

array([[0, 0],
       [0, 0],
       [1, 2]])

In [ ]:
def add_column(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [56]:
def add_column(matrix):
    m=[]
    
    for i in range(len(matrix)):
        m.append(0)
    return np.column_stack([matrix,m])

n = [[3, 2], [5, 1], [4, 7]]
add_column(n)  

array([[3, 2, 0],
       [5, 1, 0],
       [4, 7, 0]])

In [18]:
def add_column_np(n, col):
    return np.column_stack([n,col])

n = [[3, 2], [5, 1], [4, 7]]
add_column_np(n, [8,5,3])    

In [58]:
def add_matrices(m1, m2):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> b = [[2, 2], [2, 2]]
      >>> add_matrices(a, b)
      [[3, 4], [5, 6]]
      >>> c = [[8, 2], [3, 4], [5, 7]]
      >>> d = [[3, 2], [9, 2], [10, 12]]
      >>> add_matrices(c, d)
      [[11, 4], [12, 6], [15, 19]]
      >>> c
      [[8, 2], [3, 4], [5, 7]]
      >>> d
      [[3, 2], [9, 2], [10, 12]]
   """

array([[3, 2, 8],
       [5, 1, 5],
       [4, 7, 3]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [137]:
def add_matrices(m1, m2):
    m3 =[]
    for x,y in zip(m1,m2):
        m3.append(np.add(x,y))
    return np.asmatrix(m3)    
        
a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices(a, b)       

matrix([[3, 4],
        [5, 6]])

In [150]:
def add_matrices_np(m1, m2):
    
    m1 = np.matrix(m1)
    m2 = np.matrix(m2)
    
    print(m1)
    print(m2)
    return m1 + m2


a = [[1, 2], [3, 4]]
b = [[2, 2], [2, 2]]
add_matrices_np(a, b)    

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]


matrix([[3, 4],
        [5, 6]])

In [8]:
def scalar_mult(s, m):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
    """

In [151]:
def scalar_mult(s, m):
    m = np.matrix(m)
    print(m)
    return m*s
    
a = [[1, 2], [3, 4]]
scalar_mult(3, a)

[[1 2]
 [3 4]]


matrix([[ 3,  6],
        [ 9, 12]])

In [156]:
def scalar_mult(s, m):
    m = np.matrix(m)    # trasfer vectors to matrix
    shape = np.shape(m) # set columns and rows
    flat = m.flatten()   # flat vectors
    vector_muliplied = flat*s             #vector mulitplied
    return np.matrix(vector_muliplied.reshape(shape)) #reshape vector into matrix

a = [[1, 2], [3, 4], [5,6]]    
scalar_mult(3, a)                

matrix([[ 3,  6],
        [ 9, 12],
        [15, 18]])

Write functions row_times_column and matrix_mult:

In [9]:
def row_times_column(m1, row, m2, column):
    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """

In [161]:
def row_times_column(m1, row, m2, column):
    a=np.matmul(m1, m2)
    return  a[row][column]
    
row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)    

19

In [10]:
def matrix_mult(m1, m2):
   """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """

In [159]:
def matrix_mult(m1, m2):
    a=np.matmul(m1, m2)
    return  a

matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
        

array([[31, 19],
       [85, 55]])

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [179]:
def transpose(m):
    return np.transpose(m)
   
m = [[3, 4, 6]]
transpose(m)
[[3], [4], [6]]
m
[3, 4, 6]
m = [[3, 4, 6], [1, 5, 9]]
transpose(m)
[[3, 1], [4, 5], [6, 9]]
   
if name == 'main':
  import doctest
  print(doctest.testmod(verbose=True))   

NameError: name 'name' is not defined

In [169]:
def transpose(m):
    for x,y in m:
        return y,x

m = [[3, 4, 6]]
transpose(m)

ValueError: too many values to unpack (expected 2)

In [164]:
def transpose(m):
  return np.transpose(m)


m = [[3, 4, 6]]
transpose(m)

array([[3],
       [4],
       [6]])