**34. How to get all the dates corresponding to the month of July 2016**

In [14]:
import numpy as np
import random

In [10]:
print('July 2016: ')

print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July 2016: 
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random array A and B, check if they are equal**

In [34]:
x = np.random.rand(6,3)
y = np.random.rand(6,3)

print(f' array x: {x}')
print(f' array y: {y}')

print("\nResult : ", np.array_equal(x, y))

 array x: [[0.43479915 0.22965137 0.42805446]
 [0.1237475  0.27757107 0.9576629 ]
 [0.48786575 0.36225347 0.00445222]
 [0.02234393 0.28856451 0.83244914]
 [0.91010568 0.60757588 0.18185232]
 [0.18275366 0.95463729 0.67089948]]
 array y: [[0.78524821 0.41874534 0.72242483]
 [0.52329477 0.64755329 0.95423576]
 [0.69630519 0.55717855 0.49894017]
 [0.34634367 0.71071036 0.35964049]
 [0.22836136 0.36479808 0.11331685]
 [0.23373842 0.88750281 0.58827254]]

Result :  False


In [38]:
a = 10000000000
b = 10000000000
print(a == b)
print(a is b)

True
False
