In [1]:
import pandas as pd
import numpy as np

data = {
1:[2,2,1,4,5],
2:[2,2,1,4,5],
3:[2,2,1,4,5],
4:[1,2,2,1,4],
5:[1,2,2,2,1],
6:[1,2,2,1,4],
7:[1,2,3,4,5],
8:[1,2,2,1,4],
9:[1,2,3,4,2],
10:[1,2,2,1,3]}

n = 2
df_26 = pd.DataFrame(data)
#print(df_26)

indexes = []
for index, row in table.iterrows():
    counter = 0
    if index % n == 0:
        counter +=1
        indexes.append(index)


    
print(indexes)

NameError: name 'table' is not defined

In [5]:
data = {
1:[np.nan,2,np.nan,4,5],
2:[np.nan,2,3,np.nan,5],
3:[np.nan,2,np.nan,4,5],
4:[1,np.nan,3,np.nan,np.nan],
5:[1,2,np.nan,4,5],
6:[1,np.nan,3,np.nan,np.nan],
7:[1,2,3,4,5],
8:[1,np.nan,3,np.nan,np.nan],
9:[1,2,3,4,np.nan],
10:[1,np.nan,3,4,5]}


for el in data:
    

SyntaxError: unexpected EOF while parsing (<ipython-input-5-be5f55f72c2b>, line 15)

In [34]:
#add every 3rd 

total = 0
for i in range(1,50):
    if i % 3 == 0 or i % 5 == 0:
        total += i
print(list(range(1,50)))        
print(total)  


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
543


In [44]:
cf= np.array([100,200,300,400,500])
print(cf)
print('last element = ',cf[-1])
print('every 2nd element :',cf[1:4:2])

[100 200 300 400 500]
last element =  500
every 2nd element : [200 400]


In [32]:
arr = np.array([[1,2,3,4],[3,4,5,6],[3,4,5,6]])
arr2 = np.zeros((1,2,3,4))

In [33]:
print(arr.ndim)
print(arr.shape)
arr2.ndim



2
(3, 4)


4

In [34]:
arr = np.array([[1,2,3,4],[3,4,5,6],[3,4,5,6]])
print(arr.ndim)

2


In [44]:
a = 5
arr = np.array([1,2,3,4,5,67], dtype='i')
arr

array([ 1,  2,  3,  4,  5, 67], dtype=int32)

In [48]:
arr.shape
arr

array([ 1,  2,  3,  4,  5, 67], dtype=int32)

In [47]:
arr.reshape
arr

array([ 1,  2,  3,  4,  5, 67], dtype=int32)

In [51]:
eye =np.eye(9)
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
eye.shape * 4

(9, 9, 9, 9, 9, 9, 9, 9)

In [56]:
eye.reshape
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
arr = np.array([1,2,3,4,5,6])

In [62]:
arr[0:2] = 333333

arr

array([333333, 333333,      3,      4,      5,      6])

In [65]:
arr2 = arr.copy()

In [66]:
arr2

array([333333, 333333,      3,      4,      5,      6])

In [74]:
new_arr = np.array([[1,2,3],[3,2,1],[4,5,6]])
new_arrT = new_arr.T
new_arrT

array([[1, 3, 4],
       [2, 2, 5],
       [3, 1, 6]])

In [78]:
new_arr2 = np.array([[1,2,3],[3,2,1],[4,5,6]])
arr_reashaped = new_arr2.reshape(3,3)
arr_reashaped

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

In [80]:
new_arr3 = np.array([[1,2,3],[3,2,1],[4,5,6]])
arr_matrix = np.matrix(new_arr3)
arr_matrix

matrix([[1, 2, 3],
        [3, 2, 1],
        [4, 5, 6]])

In [84]:
points = np.arange(-10,10,0.1)
xs,ys = np.meshgrid(points,points)
zs = np.sin(xs) + np.cos(ys)
zs

array([[-0.29505042, -0.38153564, -0.4725924 , ..., -1.11083216,
        -1.20555066, -1.29660742],
       [-0.34517004, -0.43165526, -0.52271202, ..., -1.16095178,
        -1.25567028, -1.34672705],
       [-0.38640516, -0.47289038, -0.56394714, ..., -1.2021869 ,
        -1.2969054 , -1.38796217],
       ...,
       [-0.41834377, -0.50482899, -0.59588575, ..., -1.23412551,
        -1.32884401, -1.41990077],
       [-0.38640516, -0.47289038, -0.56394714, ..., -1.2021869 ,
        -1.2969054 , -1.38796217],
       [-0.34517004, -0.43165526, -0.52271202, ..., -1.16095178,
        -1.25567028, -1.34672705]])

In [88]:
array = np.random.normal(size=(5,4))
array

array([[-1.72776177,  1.01563828, -0.18073551,  1.46819316],
       [ 0.73982592,  2.11216374, -0.34510956,  0.87962166],
       [-0.38282389,  0.08635154,  1.28142739, -1.12945417],
       [ 0.42971451,  1.33413058, -0.39803443, -0.16643367],
       [-0.75463486,  0.55748481, -0.0178315 ,  1.14145179]])

In [108]:
np.random.uniform(-1,5,10)

array([-0.27122975,  3.43275993,  2.10650636,  4.63552638, -0.88556098,
        3.07483879,  1.51792357,  4.67397872,  2.36940567,  4.79156957])

In [104]:
arr = np.arange(19)

np.random.shuffle(arr)
arr

array([14, 18, 17,  8, 16,  9,  3,  4, 10, 11,  7, 12,  2, 15,  1, 13,  6,
        0,  5])

In [105]:
np.random.permutation(arr)
arr

array([14, 18, 17,  8, 16,  9,  3,  4, 10, 11,  7, 12,  2, 15,  1, 13,  6,
        0,  5])

In [112]:
arr = np.arange(8)
print(arr)

mat = arr.reshape((4,2))
print(mat)

mat_flat = mat.flatten()
print(mat_flat)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1 2 3 4 5 6 7]


In [113]:
a= pd.Series([4,6,-5,3])

print(a)

0    4
1    6
2   -5
3    3
dtype: int64


In [115]:
a= pd.Series([4,6,-5,3], index =['x1','x2','y1','y2'])
a

x1    4
x2    6
y1   -5
y2    3
dtype: int64

In [119]:
a_sum =a.sum()
a

x1    4
x2    6
y1   -5
y2    3
dtype: int64

In [121]:
df = pd.DataFrame({"Data1": [ 10,20,30],  "Data2": [ 40,50,60]})

norm_df = (df-df.min())/(df.max()-df.min())
print(norm_df)

   Data1  Data2
0    0.0    0.0
1    0.5    0.5
2    1.0    1.0


In [130]:
df = pd.read_excel(r'C:\Users\Wojtek\OneDrive\Desktop\STRIVE SCHOOL\valuation.xlsx')
print(df)

    Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0          NaN         NaN         NaN         NaN         NaN         NaN   
1          NaN         NaN         NaN         NaN         NaN         NaN   
2          NaN         NaN         NaN         NaN         NaN         NaN   
3          NaN         NaN         NaN         NaN         NaN         NaN   
4          NaN         NaN         NaN         NaN         NaN         NaN   
5          NaN         NaN         NaN         NaN         NaN         NaN   
6          NaN         NaN         NaN         NaN         NaN         NaN   
7          NaN         NaN         NaN         NaN         NaN         NaN   
8          NaN         NaN         NaN         NaN         NaN         NaN   
9          NaN         NaN         NaN         NaN         NaN         NaN   
10         NaN         NaN         NaN         NaN         NaN         NaN   
11         NaN         NaN         NaN         NaN         NaN  

In [134]:
w = np.random.rand(5,5)#
w

array([[0.69725798, 0.60472345, 0.81882146, 0.66939882, 0.14884215],
       [0.57513864, 0.05758803, 0.64869395, 0.92049127, 0.92263045],
       [0.72647555, 0.18078893, 0.37338039, 0.37527081, 0.14694305],
       [0.45155443, 0.95835555, 0.31343265, 0.26198607, 0.17121535],
       [0.27398601, 0.36346079, 0.6584577 , 0.52732488, 0.44583092]])

In [136]:
np.round(w)
w

array([[0.69725798, 0.60472345, 0.81882146, 0.66939882, 0.14884215],
       [0.57513864, 0.05758803, 0.64869395, 0.92049127, 0.92263045],
       [0.72647555, 0.18078893, 0.37338039, 0.37527081, 0.14694305],
       [0.45155443, 0.95835555, 0.31343265, 0.26198607, 0.17121535],
       [0.27398601, 0.36346079, 0.6584577 , 0.52732488, 0.44583092]])

In [153]:
data={
    'name':['Maria','Clara','Juan', 'Ana'],
    'age':[12,65,34,76]
}

a = pd.DataFrame(data, index=['m','c','j','a'])

print(a)
print("                 ")
print(a.loc['j':'a'])
print("                 ")
print(a.iloc[1:2])


    name  age
m  Maria   12
c  Clara   65
j   Juan   34
a    Ana   76
                 
   name  age
j  Juan   34
a   Ana   76
                 
    name  age
c  Clara   65


In [166]:
a_drop = a.drop('age',axis = 1)
print(a_drop)
print(a)

    name
m  Maria
c  Clara
j   Juan
a    Ana
    name  age
m  Maria   12
c  Clara   65
j   Juan   34
a    Ana   76


In [164]:
a_drop2 = a.drop('c')
print(a)
print(a_drop2)

    name  age
m  Maria   12
c  Clara   65
j   Juan   34
a    Ana   76
    name  age
m  Maria   12
j   Juan   34
a    Ana   76


In [170]:
x = lambda a: a*10
print(x(20))

200


In [186]:
print(a)

a_sorted = a.sort_values(by='age', ascending =False)
print(a_sorted)

    name  age
m  Maria   12
c  Clara   65
j   Juan   34
a    Ana   76
    name  age
a    Ana   76
c  Clara   65
j   Juan   34
m  Maria   12


In [190]:
 i =1
 while i %3==0:
     i += 1
     break
print(i)

1


True