In [ ]:
# Install torch and torchvision on your computer
# It's convenient to create a virtual env for that

In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
# set the torch manual seed to 42

torch.manual_seed(42)

In [15]:
# Create a tensor of shape (5,) and store in the features variable


features = torch.arange(5.)
features

tensor([0., 1., 2., 3., 4.])

In [17]:
# Generate a tensor called weights with the same shape of features
# Hint: search torch.rand_like


weights = torch.rand_like(features)
weights

tensor([0.9346, 0.5936, 0.8694, 0.5677, 0.7411])

In [18]:
assert weights.shape == features.shape

In [21]:
bias = torch.randn((1,1))

In [22]:
bias

tensor([[-1.2284]])

In [32]:
# Implement the sigmoid function by using torch
def sigmoid(x):
    sig = nn.Sigmoid()
    return sig(x)
    

In [27]:
# Use torch.dot function for multiplying weights and features and
# add the bias to the result. Store the result into the score variable

score = torch.dot(weights, features)+bias 

score



tensor([[5.7715]])

In [28]:
assert score.shape == (1,1)

In [33]:
# Use the defined sigmoid function to activate the score.
# Store the result in the prob variable

prob = sigmoid(score)


In [47]:
assert prob.shape == (1,1)

In [35]:
# Convert the a numpy array into a torch tensor
# Store it in the b variable
a = np.random.rand(4, 3)
a
b = torch.tensor(a)
print(a)
print(b)

[[0.67404041 0.63796454 0.3660872 ]
 [0.53288274 0.81396607 0.29299693]
 [0.78707531 0.43991866 0.7093747 ]
 [0.02188232 0.56803977 0.29234651]]
tensor([[0.6740, 0.6380, 0.3661],
        [0.5329, 0.8140, 0.2930],
        [0.7871, 0.4399, 0.7094],
        [0.0219, 0.5680, 0.2923]], dtype=torch.float64)


In [36]:
assert b.shape == (4,3) 

In [39]:
# Do the opposite now. From the given tensor a convert it a numpy array
# Store the result in b
a = torch.tensor([1,2])
a
b = a.numpy()
print(a)
print(b)

tensor([1, 2])
[1 2]


In [40]:
assert type(b) == np.ndarray

In [59]:
# Reshape the given v tensor in a 10x10 tensor.
# Store the result in v_reshaped
# You can use various methods: reshape, view, resize... Check all of them

v = torch.randn((100,1))
v_reshaped = torch.reshape(v,(10,10))
v_reshaped = v.view(10,10)
v_reshaped = 
#print(v)
print(v_reshaped)

tensor([[-0.0547,  0.0477, -0.8638, -1.1419, -0.8292,  0.3263, -0.1410,  0.8008,
         -1.3405, -0.5562],
        [ 1.1731,  0.6860,  0.8626, -0.4877,  0.6470, -1.8527,  0.7437, -0.0328,
          1.0600,  0.0039],
        [-0.6952,  1.2538,  0.0902,  1.9940,  1.7811, -0.2937,  0.5243,  1.0186,
         -0.1513, -0.9719],
        [-1.0718,  1.2559, -1.0704, -0.6159, -1.0195,  0.3848,  0.2943,  0.6351,
          0.2036, -0.1810],
        [-0.6895, -0.2830,  0.6600, -0.1619,  0.8861,  1.8163,  0.2068,  0.1198,
         -0.6674,  1.6183],
        [-0.2644,  1.3541, -0.0709,  2.1726,  2.2334,  0.2225,  0.6974,  0.8342,
         -1.0987,  0.5675],
        [ 0.8284, -0.0056,  0.3184, -0.2403,  1.0238,  2.1327,  0.2335,  1.2005,
         -1.2669, -0.6660],
        [-1.7441,  0.1139,  0.7174, -0.2303,  0.7148,  1.4437,  0.1961,  1.0502,
          0.7995,  0.1927],
        [-1.2479, -0.0926,  0.6534,  0.1637, -0.1790, -0.1972, -0.6042,  1.2439,
         -1.7002, -1.2209],
        [-1.3159, -

In [65]:
# create a tensor with shape (16, 32, 32, 3) containing only ones
# Store it in the ones variable
ones = torch.ones(16,32,32,3)


In [66]:
assert ones.shape == (16, 32, 32, 3)

In [70]:
import pandas as pd
import matplotlib.pyplot as plt
# load and plot the data using scatterplot with different colors for labels
data = pd.read_csv('data.csv', header=None)
data

0         1  2
0   0.78051 -0.063669  1
1   0.28774  0.291390  1
2   0.40714  0.178780  1
3   0.29230  0.421700  1
4   0.50922  0.352560  1
..      ...       ... ..
95  0.77029  0.701400  0
96  0.73156  0.717820  0
97  0.44556  0.579910  0
98  0.85275  0.859870  0
99  0.51912  0.623590  0

[100 rows x 3 columns]

In [72]:

plt.scatter(x=data[:,0], y= data[:,1], c=data[:,2])

TypeError: '(slice(None, None, None), 0)' is an invalid key